apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: test
  name: include-label
spec:
  containers:
    - image: busybox
      name: a
      command:
        - sleep
        - "9999"
