apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: test
  name: include-label-and-namespace-test2
  namespace: test2
spec:
  containers:
    - image: busybox
      name: a
      command:
        - sleep
        - "9999"
