run:
  timeout: 5m

linters-settings:
  gocyclo:
    min-complexity: 20
  govet:
    enable:
      - shadow
#      - fieldalignment
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - errcheck
    - errorlint
    - exhaustive
    - gocyclo
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nestif
    - nilerr
    - noctx
    - prealloc
    - rowserrcheck
    - staticcheck
    - typecheck
    - unconvert
