# permissions for end users to view instrumentations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instrumentation-viewer-role
rules:
- apiGroups:
  - newrelic.com
  resources:
  - instrumentations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - newrelic.com
  resources:
  - instrumentations/status
  verbs:
  - get
