apiVersion: newrelic.com/v1alpha1
kind: Instrumentation
metadata:
  name: newrelic-instrumentation
spec:
  java:
    image: ghcr.io/newrelic-experimental/newrelic-agent-operator/instrumentation-java:latest
  nodejs:
    image: ghcr.io/newrelic-experimental/newrelic-agent-operator/instrumentation-nodejs:latest
  python:
    image: ghcr.io/newrelic-experimental/newrelic-agent-operator/instrumentation-python:latest
  dotnet:
    image: ghcr.io/newrelic-experimental/newrelic-agent-operator/instrumentation-dotnet:latest
  php:
    image: ghcr.io/newrelic-experimental/newrelic-agent-operator/instrumentation-php:latest
  go:
    image: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:latest