/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"context"
	"crypto/tls"
	"flag"
	"fmt"
	"net"
	"net/http"
	"os"
	"runtime"
	"strconv"
	"strings"
	"time"

	"github.com/go-logr/logr"
	openshift_routev1 "github.com/openshift/api/route/v1"
	k8sruntime "k8s.io/apimachinery/pkg/runtime"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"
	k8sscheme "k8s.io/client-go/kubernetes/scheme"
	_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
	"k8s.io/klog/v2"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/cache"
	"sigs.k8s.io/controller-runtime/pkg/healthz"
	"sigs.k8s.io/controller-runtime/pkg/log/zap"
	"sigs.k8s.io/controller-runtime/pkg/manager"
	"sigs.k8s.io/controller-runtime/pkg/metrics/filters"
	metricsserver "sigs.k8s.io/controller-runtime/pkg/metrics/server"
	webhookruntime "sigs.k8s.io/controller-runtime/pkg/webhook"

	newreliccomv1alpha2 "github.com/newrelic/k8s-agents-operator/api/v1alpha2"
	newreliccomv1beta1 "github.com/newrelic/k8s-agents-operator/api/v1beta1"
	newreliccomv1beta2 "github.com/newrelic/k8s-agents-operator/api/v1beta2"
	newreliccomv1beta3 "github.com/newrelic/k8s-agents-operator/api/v1beta3"
	"github.com/newrelic/k8s-agents-operator/internal/autodetect"
	"github.com/newrelic/k8s-agents-operator/internal/config"
	"github.com/newrelic/k8s-agents-operator/internal/controller"
	"github.com/newrelic/k8s-agents-operator/internal/instrumentation"
	instrumentationupgrade "github.com/newrelic/k8s-agents-operator/internal/migrate/upgrade"
	"github.com/newrelic/k8s-agents-operator/internal/version"
	"github.com/newrelic/k8s-agents-operator/internal/webhook"
	// +kubebuilder:scaffold:imports
)

var healthCheckTickInterval = time.Second * 15
var setupLog = ctrl.Log.WithName("setup")

func getScheme() *k8sruntime.Scheme {
	var scheme = k8sruntime.NewScheme()
	sb := k8sruntime.NewSchemeBuilder(
		k8sscheme.AddToScheme,
		openshift_routev1.AddToScheme,
		newreliccomv1alpha2.AddToScheme,
		newreliccomv1beta1.AddToScheme,
		newreliccomv1beta2.AddToScheme,
		newreliccomv1beta3.AddToScheme,
	)
	utilruntime.Must(sb.AddToScheme(scheme))
	// +kubebuilder:scaffold:scheme
	return scheme
}

type managerConfig struct {
	leaseDuration                 time.Duration
	renewDeadline                 time.Duration
	retryPeriod                   time.Duration
	webhookBindAddr               string
	webhookCertDir                string
	metricsBindAddr               string
	healthBindAddr                string
	enableHTTP2                   bool
	secureMetrics                 bool
	enableLeaderElection          bool
	leaderElectionID              string
	leaderElectionReleaseOnCancel bool
}

func getManagerOptions(scheme *k8sruntime.Scheme, cfg managerConfig) ctrl.Options {
	var webhookTlsOpts []func(*tls.Config)
	var metricsTlsOpts []func(*tls.Config)
	// if the enable-http2 flag is false (the default), http/2 should be disabled
	// due to its vulnerabilities. More specifically, disabling http/2 will
	// prevent from being vulnerable to the HTTP/2 Stream Cancellation and
	// Rapid Reset CVEs. For more information see:
	// - https://github.com/advisories/GHSA-qppj-fm5r-hxr3
	// - https://github.com/advisories/GHSA-4374-p667-p6c8
	disableHTTP2 := func(component string) func(c *tls.Config) {
		return func(c *tls.Config) {
			setupLog.Info("disabling http/2", "component", component)
			c.NextProtos = []string{"http/1.1"}
		}
	}
	if !cfg.enableHTTP2 {
		webhookTlsOpts = append(webhookTlsOpts, disableHTTP2("webhook"))
		metricsTlsOpts = append(webhookTlsOpts, disableHTTP2("metrics"))
	}
	webhookHost, webhookPort, err := net.SplitHostPort(cfg.webhookBindAddr)
	if err != nil {
		setupLog.Error(err, "invalid webhook bind address")
		os.Exit(1)
	}
	webhooksvcport, err := strconv.Atoi(webhookPort)
	if err != nil {
		setupLog.Error(err, "invalid webhook service port")
		os.Exit(1)
	}
	webhookServer := webhookruntime.NewServer(webhookruntime.Options{
		TLSOpts: webhookTlsOpts,
		Port:    webhooksvcport,
		Host:    webhookHost,
		CertDir: cfg.webhookCertDir,
	})
	metricsServerOptions := metricsserver.Options{
		BindAddress:   cfg.metricsBindAddr,
		SecureServing: cfg.secureMetrics,
		// TODO(user): TLSOpts is used to allow configuring the TLS config used for the server. If certificates are
		// not provided, self-signed certificates will be generated by default. This option is not recommended for
		// production environments as self-signed certificates do not offer the same level of trust and security
		// as certificates issued by a trusted Certificate Authority (CA). The primary risk is potentially allowing
		// unauthorized access to sensitive metrics data. Consider replacing with CertDir, CertName, and KeyName
		// to provide certificates, ensuring the server communicates using trusted and secure certificates.
		TLSOpts: metricsTlsOpts,
	}
	if cfg.secureMetrics {
		// FilterProvider is used to protect the metrics endpoint with authn/authz.
		// These configurations ensure that only authorized users and service accounts
		// can access the metrics endpoint. The RBAC are configured in 'config/rbac/kustomization.yaml'. More info:
		// https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.18.4/pkg/metrics/filters#WithAuthenticationAndAuthorization
		metricsServerOptions.FilterProvider = filters.WithAuthenticationAndAuthorization
	}
	mgrOptions := ctrl.Options{
		Scheme:                 scheme,
		Metrics:                metricsServerOptions,
		WebhookServer:          webhookServer,
		HealthProbeBindAddress: cfg.healthBindAddr,
		LeaderElection:         cfg.enableLeaderElection,
		LeaderElectionID:       cfg.leaderElectionID,
		// LeaderElectionReleaseOnCancel defines if the leader should step down voluntarily
		// when the Manager ends. This requires the binary to immediately end when the
		// Manager is stopped, otherwise, this setting is unsafe. Setting this significantly
		// speeds up voluntary leader transitions as the new leader don't have to wait
		// LeaseDuration time first.
		//
		// In the default scaffold provided, the program ends immediately after
		// the manager stops, so would be fine to enable this option. However,
		// if you are doing or is intended to do any operation such as perform cleanups
		// after the manager stops then its usage might be unsafe.
		LeaderElectionReleaseOnCancel: cfg.leaderElectionReleaseOnCancel,
		LeaseDuration:                 &cfg.leaseDuration,
		RenewDeadline:                 &cfg.renewDeadline,
		RetryPeriod:                   &cfg.retryPeriod,
	}
	return mgrOptions
}

type mainFlags struct {
	metricsAddr          string
	probeAddr            string
	webhooksvc           string
	enableLeaderElection bool
	secureMetrics        bool
	enableHTTP2          bool
}

func parseArgs() (mainFlags, zap.Options) {
	var flags mainFlags
	flag.StringVar(&flags.metricsAddr, "metrics-bind-address", "0", "The address the metrics endpoint binds to.  Use :8443 for HTTPS or :8080 for HTTP, or leave as 0 to disable the metrics service.")
	flag.StringVar(&flags.probeAddr, "health-probe-bind-address", ":8081", "The address the probe endpoint binds to.")
	flag.StringVar(&flags.webhooksvc, "webhook-service-bind-address", ":9443", "The address the webhook service endpoint binds to.")
	flag.BoolVar(&flags.enableLeaderElection, "leader-elect", false, "Enable leader election for controller manager.  Enabling this will ensure there is only one active controller manager.")
	flag.BoolVar(&flags.secureMetrics, "metrics-secure", true, "If set, the metrics endpoint is served securely via HTTPS. Use --metrics-secure=false to use HTTP instead.")
	flag.BoolVar(&flags.enableHTTP2, "enable-http2", true, "If set, HTTP/2 will be enabled for the metrics and webhook servers")

	zapOpts := zap.Options{}
	zapOpts.BindFlags(flag.CommandLine)
	flag.Parse()
	return flags, zapOpts
}

func main() {
	scheme := getScheme()
	flags, opts := parseArgs()

	logger := zap.New(zap.UseFlagOptions(&opts))
	ctrl.SetLogger(logger)
	klog.SetLogger(logger)

	operatorNamespace := os.Getenv("OPERATOR_NAMESPACE")
	if operatorNamespace == "" {
		setupLog.Info("env var OPERATOR_NAMESPACE is required")
		os.Exit(1)
	}

	v := version.Get()
	setupLog.Info("Starting the Kubernetes Agents Operator",
		"k8s-agents-operator", v.Operator,
		"running-namespace", operatorNamespace,
		"build-date", v.BuildDate,
		"go-version", v.Go,
		"go-arch", runtime.GOARCH,
		"go-os", runtime.GOOS,
	)

	restConfig := ctrl.GetConfigOrDie()
	// builds the operator's configuration
	ad, err := autodetect.New(restConfig)
	if err != nil {
		setupLog.Error(err, "failed to setup auto-detect routine")
		os.Exit(1)
	}
	cfg := config.New(
		config.WithLogger(ctrl.Log.WithName("config")),
		config.WithVersion(v),
		config.WithAutoDetect(ad),
	)

	// see https://github.com/openshift/library-go/blob/4362aa519714a4b62b00ab8318197ba2bba51cb7/pkg/config/leaderelection/leaderelection.go#L104
	leaseDuration := time.Second * 137
	renewDeadline := time.Second * 107
	retryPeriod := time.Second * 26
	mgrOptions := getManagerOptions(scheme, managerConfig{
		metricsBindAddr:               flags.metricsAddr,
		secureMetrics:                 flags.secureMetrics,
		webhookBindAddr:               flags.webhooksvc,
		healthBindAddr:                flags.probeAddr,
		enableLeaderElection:          flags.enableLeaderElection,
		leaderElectionID:              "9f7554c3.newrelic.com",
		leaderElectionReleaseOnCancel: true,
		leaseDuration:                 leaseDuration,
		renewDeadline:                 renewDeadline,
		retryPeriod:                   retryPeriod,
		enableHTTP2:                   flags.enableHTTP2,
	})

	watchNamespace, found := os.LookupEnv("WATCH_NAMESPACE")
	if found {
		setupLog.Info("watching namespace(s)", "namespaces", watchNamespace)
	} else {
		setupLog.Info("the env var WATCH_NAMESPACE isn't set, watching all namespaces")
	}
	if watchNamespace != "" {
		nsDefaults := map[string]cache.Config{}
		for _, watchNamespaceEntry := range strings.Split(watchNamespace, ",") {
			nsDefaults[watchNamespaceEntry] = cache.Config{}
		}
		mgrOptions.Cache = cache.Options{DefaultNamespaces: nsDefaults}
	}

	mgr, err := ctrl.NewManager(restConfig, mgrOptions)
	if err != nil {
		setupLog.Error(err, "unable to start manager")
		os.Exit(1)
	}

	// TODO: Use controller paradigm & investigate below
	ctx := ctrl.SetupSignalHandler()
	err = addDependencies(ctx, mgr, cfg)
	if err != nil {
		setupLog.Error(err, "failed to add/run bootstrap dependencies to the controller manager")
		os.Exit(1)
	}

	instrumentationStatusUpdater := instrumentation.NewInstrumentationStatusUpdater(mgr.GetClient())
	healthApi := instrumentation.NewHealthCheckApi(http.DefaultClient)
	healthMonitor := instrumentation.NewHealthMonitor(
		instrumentationStatusUpdater, healthApi, healthCheckTickInterval, 50, 50, 2,
	)
	go func() {
		<-ctx.Done()
		logger.Info("Shutting down health checker")
		stopCtx, stopCtxCancel := context.WithTimeout(context.Background(), 25*time.Second)
		defer stopCtxCancel()
		if err = healthMonitor.Stop(stopCtx); err != nil {
			setupLog.Error(err, "failed to stop health checker")
		} else {
			logger.Info("Shut down health checker")
		}
	}()

	if err = setupReconcilers(mgr, healthMonitor, operatorNamespace); err != nil {
		setupLog.Error(err, "failed to setup reconcilers")
		os.Exit(1)
	}
	if os.Getenv("ENABLE_WEBHOOKS") != "false" {
		if err = setupWebhooks(mgr, operatorNamespace); err != nil {
			setupLog.Error(err, "failed to setup webhooks")
			os.Exit(1)
		}
	} else {
		ctrl.Log.Info("Webhooks are disabled, operator is running an unsupported mode", "ENABLE_WEBHOOKS", "false")
	}
	// +kubebuilder:scaffold:builder

	if err = registerApiHealth(mgr); err != nil {
		setupLog.Error(err, "failed to register api healthz and readyz")
		os.Exit(1)
	}

	setupLog.Info("starting manager")
	if err := mgr.Start(ctx); err != nil {
		setupLog.Error(err, "problem running manager")
		os.Exit(1)
	}
}

func registerApiHealth(mgr manager.Manager) error {
	if err := mgr.AddHealthzCheck("healthz", healthz.Ping); err != nil {
		return fmt.Errorf("unable to register api health check: %w", err)
	}
	if err := mgr.AddReadyzCheck("readyz", healthz.Ping); err != nil {
		return fmt.Errorf("unable to register api ready check: %w", err)
	}
	return nil
}

func setupWebhooks(mgr manager.Manager, operatorNamespace string) error {
	if err := setupInstrumentationWebhooks(mgr, operatorNamespace); err != nil {
		return err
	}
	return setupPodMutationWebhook(mgr, operatorNamespace, ctrl.Log.WithName("mutation-webhook"))
}

func setupInstrumentationWebhooks(mgr manager.Manager, operatorNamespace string) error {
	type wehhookSetup struct {
		name  string
		setup func(mgr ctrl.Manager, operatorNamespace string) error
	}
	webhooks := []wehhookSetup{
		{name: "v1alpha2", setup: newreliccomv1alpha2.SetupWebhookWithManager},
		{name: "v1beta1", setup: newreliccomv1beta1.SetupWebhookWithManager},
		{name: "v1beta2", setup: newreliccomv1beta2.SetupWebhookWithManager},
		{name: "v1beta3", setup: newreliccomv1beta3.SetupWebhookWithManager},
	}
	for _, webhook := range webhooks {
		if err := webhook.setup(mgr, operatorNamespace); err != nil {
			return fmt.Errorf("unable to register %s.instrumentation webhook: %v", webhook.name, err)
		}
	}
	return nil
}

func setupPodMutationWebhook(mgr manager.Manager, operatorNamespace string, logger logr.Logger) error {
	// Register the Pod mutation webhook
	if err := webhook.SetupWebhookWithManager(mgr, operatorNamespace, logger); err != nil {
		return fmt.Errorf("unable to register pod mutation webhook: %w", err)
	}
	return nil
}

func setupReconcilers(mgr manager.Manager, healthMonitor *instrumentation.HealthMonitor, operatorNamespace string) error {
	var err error
	if err = (&controller.NamespaceReconciler{
		Client: mgr.GetClient(),
		Scheme: mgr.GetScheme(),
	}).SetupWithManager(mgr, healthMonitor); err != nil {
		return fmt.Errorf("unable to create namespace controller: %w", err)
	}
	if err = (&controller.PodReconciler{
		Client: mgr.GetClient(),
		Scheme: mgr.GetScheme(),
	}).SetupWithManager(mgr, healthMonitor, operatorNamespace); err != nil {
		return fmt.Errorf("unable to create pod controller: %w", err)
	}
	if err = (&controller.InstrumentationReconciler{
		Client: mgr.GetClient(),
		Scheme: mgr.GetScheme(),
	}).SetupWithManager(mgr, healthMonitor, operatorNamespace); err != nil {
		return fmt.Errorf("unable to create instrumentation controller: %w", err)
	}
	return nil
}

func addDependencies(_ context.Context, mgr ctrl.Manager, cfg config.Config) error {
	// run the auto-detect mechanism for the configuration
	err := mgr.Add(manager.RunnableFunc(func(_ context.Context) error {
		return cfg.StartAutoDetect()
	}))
	if err != nil {
		return fmt.Errorf("failed to start the auto-detect mechanism: %w", err)
	}

	// adds the upgrade mechanism to be executed once the manager is ready
	err = mgr.Add(manager.RunnableFunc(func(c context.Context) error {
		u := &instrumentationupgrade.InstrumentationUpgrade{
			Logger: ctrl.Log.WithName("instrumentation-upgrade"),
			Client: mgr.GetClient(),
		}
		return u.ManagedInstances(c)
	}))
	if err != nil {
		return fmt.Errorf("failed to upgrade Instrumentation instances: %w", err)
	}
	return nil
}
