apiVersion: v1
kind: Service
metadata:
  name: {{ template "newrelic-agent-operator.fullname" . }}
  labels:
    control-plane: controller-manager
  {{- include "newrelic-agent-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    app.kubernetes.io/name: {{ include "newrelic-agent-operator.chart" . }}
    control-plane: controller-manager
  {{- include "newrelic-agent-operator.labels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 -}}