{{- if and .Values.admissionWebhooks.create .Values.admissionWebhooks.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "k8s-agents-operator.fullname" . }}-serving-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-agents-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ template "k8s-agents-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc'
  - '{{ template "k8s-agents-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.{{ .Values.kubernetesClusterDomain }}'
  issuerRef:
    kind: Issuer
    name: '{{ template "k8s-agents-operator.fullname" . }}-selfsigned-issuer'
  secretName: {{ template "k8s-agents-operator.certificateSecret" . }}
  subject:
    organizationalUnits:
    - k8s-agents-operator
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "k8s-agents-operator.fullname" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-agents-operator.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
