{{- if and .Values.admissionWebhooks.create .Values.admissionWebhooks.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "newrelic.common.naming.fullname" . }}-serving-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "newrelic.common.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "newrelic.common.naming.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc'
  - '{{ include "newrelic.common.naming.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.{{ .Values.kubernetesClusterDomain }}'
  issuerRef:
    kind: Issuer
    name: {{ include "newrelic.common.naming.fullname" . }}-selfsigned-issuer
  secretName: {{ include "k8s-agents-operator.certificateSecret.fullname" . }}
  subject:
    organizationalUnits:
    - k8s-agents-operator
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "newrelic.common.naming.fullname" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "newrelic.common.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
