{{- $licenseKey := include "newrelic-agent-operator.licenseKey" . -}}
{{- if $licenseKey }}
apiVersion: v1
kind: Secret
metadata:
  name: "newrelic-key-secret"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "newrelic-agent-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  new_relic_license_key: {{ $licenseKey | b64enc }}
{{- end }}