apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "newrelic.common.naming.fullname" . }}-metrics-reader
  labels:
    {{- include "newrelic.common.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
