apiVersion: v1
kind: Service
metadata:
  name: {{ template "k8s-agents-operator.fullname" . }}
  labels:
    control-plane: controller-manager
  {{- include "k8s-agents-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "k8s-agents-operator.labels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 -}}