apiVersion: v1
kind: Service
metadata:
  name: {{ template "k8s-agents-operator.fullname" . }}-webhook-service
  labels:
  {{- include "k8s-agents-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    control-plane: controller-manager
  {{- include "k8s-agents-operator.labels" . | nindent 4 }}
  ports:
	{{- .Values.webhookService.ports | toYaml | nindent 2 -}}