apiVersion: v1
kind: Service
metadata:
  name: {{ template "k8s-agents-operator.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "newrelic.common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    {{- include "newrelic.common.labels.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
  ports:
	{{- .Values.webhookService.ports | toYaml | nindent 2 -}}
